version: "3.8"
services:
  backend:
    image: "huseyin11/spring-boot-react-fullstack-example-demo:28.01.2023.17.28.00"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
